FROM golang:1.16.5-buster

WORKDIR /usr/src/app

COPY ./ ./
RUN go build

ENV EXTRA_ARGS= GITHUB_TOKEN= JIRA_TOKEN= JIRA_USERNAME= WEBHOOK_URL=

CMD ["sh", "-c", "./github_jira synchelpwanted --webhook-url $WEBHOOK_URL --jira-token $JIRA_TOKEN --jira-username $JIRA_USERNAME --github-token $GITHUB_TOKEN $EXTRA_ARGS"]
